# Site settings
title:
email: mladeznicka.konfera@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://mk.baptist.sk" # the base hostname & protocol for your site
url: "bjb-sk.github.io" # the base hostname & protocol for your site
facebook: https://www.facebook.com/events/993799814144903
youtube: https://www.youtube.com/channel/UCDIZcaRg3nfl7aD9slJObTg
twitter_username:
github_username:
description: Mládežnícka konferencia 2018 (22.-24.02 2019, BB). Nadupaný víkend plný zaujímavých tém, seminárov, chvál, vzácnych hostí a ďalších skvelých vecí. Neváhaj a zaregistruj sa čím skôr. Tešíme sa na Teba!
image: https://res.cloudinary.com/m1n0/image/upload/v1543962047/mk-2019-banner_mdgnn5.png
title: MK2019
year: 2019

# Build settings
markdown: kramdown
