# Site settings
title:
email: mladeznicka.konfera@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mk.baptist.sk" # the base hostname & protocol for your site
facebook: https://www.facebook.com/events/933096596790303
youtube: https://www.youtube.com/channel/UCDIZcaRg3nfl7aD9slJObTg
twitter_username:
github_username:

# Build settings
markdown: kramdown
